name: Java CI/CD + AWS Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ DEBUG (VERY IMPORTANT - SEE FILES)
      - name: Show Project Structure
        run: ls -R

      # ✅ VERIFY pom.xml exists
      - name: Check pom.xml
        run: ls app

      # ✅ CORRECT BUILD (NO MORE ERROR)
      - name: Build Java App
        run: |
          cd app
          mvn clean package -DskipTests

      # ✅ TERRAFORM
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Show Outputs
        run: |
          cd terraform
          terraform output